book_project/book_project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from books_app import views
from book_project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login),  # 登录
    path('get_img/', views.get_validCode_img),  # 获取随机验证图片
    path('logout/', views.logout),  # 退出
    path('register/', views.register),  # 注册
    path('book/', views.book),  # 书籍
    re_path('^$', views.book),  # 主页也是书籍
    path('add_books/', views.add_books),  # 添加书籍
    path('add_publish/', views.add_publish),  # 添加出版社
    path('add_author/', views.add_author),  # 添加作者
    re_path(r'book/(\d+)/delete_book/$', views.delete_book),  # 删除书籍
    re_path(r'book/(\d+)/change_book/$', views.change_book),  # 编辑书籍
    re_path(r'book/(\d+)/delete_publish/$', views.delete_publish),  # 删除出版社
    re_path(r'book/(\d+)/change_publish/$', views.change_publish),  # 编辑出版社
    re_path(r'book/(\d+)/delete_author/$', views.delete_author),  # 删除作者
    re_path(r'book/(\d+)/change_author/$', views.change_author),  # 编辑作者
    re_path(r'book/(.+)/author_list/$', views.author_list),  # 查看作者所写书籍列表
    re_path(r'book/(\d+)/publish_list/$', views.publish_list),  # 查看出版社出版书籍列表
    re_path(r"media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),  # media配置:存放用户头像
]

book_project/books_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class UserInfo(AbstractUser):
    """用户信息"""
    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11, null=True, unique=True)  # 手机号，可以为空，且唯一
    avatar = models.FileField(upload_to='avatars/', default='/avatars/default.png')
    # 头像，存放地址的相对路径，初始图片路径
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # 创建时间，生成该字段时不用赋值，当前时间就是该值

    def __str__(self):
        """
        打印时显示的信息
        :return: 用户名
        """
        return self.username


class Publish(models.Model):
    """出版社信息表"""
    nid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)  # 名字
    city = models.CharField(max_length=32)  # 所在城市
    email = models.EmailField()  # 邮箱

    def __str__(self):
        """
        打印时显示的信息
        :return: 出版社的名字
        """
        return self.name


class Author(models.Model):
    """作者信息表"""
    nid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    age = models.IntegerField()  # 年龄

    def __str__(self):
        """
        打印时显示的信息
        :return: 作者的名字
        """
        return self.name


class Book(models.Model):
    """书籍信息表"""
    nid = models.AutoField(primary_key=True)  # 主键，自增
    title = models.CharField(max_length=32)
    publishDate = models.DateField(default='2020-01-01')  # 出版日期
    price = models.DecimalField(max_digits=5, decimal_places=2, default=100.00)  # 价格,最多五位数，小数点后两位

    publish = models.ForeignKey(to='Publish', to_field='nid', on_delete=models.CASCADE)  # 与出版社表建立多对一关系
    authors = models.ManyToManyField(to='Author')  # 与Author建立多对多关系

    def __str__(self):
        """
        打印时显示的信息
        :return: 书名
        """
        return self.title

book_project/templates/add_author.html
{% extends 'base.html' %}


{#标题#}
{% block title %}
    <title>作者</title>
{% endblock title %}

{#头部信息#}
{% block head %}
    <span>添&nbsp;加&nbsp;作&nbsp;者&nbsp;页&nbsp;面</span>
{% endblock %}

{#form表单#}
{% block con %}
    <form action="/add_author/" method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="row">
                <div class="col-xs-6 col-md-offset-2">
                    <label for="">{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red" class="pull-right">{{ field.errors.0 }}</span>
                </div>
            </div>
        {% endfor %}
        <br>
        <input type="submit" class="btn btn-success col-md-offset-7">
    </form>
{% endblock %}

book_project/templates/add_books.html
{% extends 'base.html' %}


{#标题#}
{% block title %}
    <title>add_books</title>
{% endblock title %}

{#头部信息#}
{% block head %}
    <span>添&nbsp;加&nbsp;书&nbsp;籍&nbsp;页&nbsp;面</span>
{% endblock %}

{#form表单#}
{% block con %}
    <form action="" method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="row">
                <div class="col-xs-6 col-md-offset-2">
                    <label for="">{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red" class="pull-right">{{ field.errors.0 }}</span>
                </div>
            </div>
        {% endfor %}
        <br>
        <input type="submit" class="btn btn-success col-md-offset-7">
    </form>
{% endblock %}

book_project/templates/add_publish.html
{% extends 'base.html' %}


{#标题#}
{% block title %}
    <title>add_books</title>
{% endblock title %}

{#头部信息#}
{% block head %}
    <span>添&nbsp;加&nbsp;出&nbsp;版&nbsp;社&nbsp;页&nbsp;面</span>
{% endblock %}

{#form表单#}
{% block con %}
    <form action="/add_publish/" method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="row">
                <div class="col-xs-6 col-md-offset-2">
                    <label for="">{{ field.label }}</label>
                    {{ field }}
                    <span style="color: red" class="pull-right">{{ field.errors.0 }}</span>
                </div>
            </div>
        {% endfor %}
        <br>
        <input type="submit" class="btn btn-success col-md-offset-7">
    </form>
{% endblock %}

book_project/templates/author_list.html
{% extends 'base.html' %}


{#标题#}
{% block title %}
    <title>author_list</title>
{% endblock title %}

{#头部信息#}
{% block head %}
    <span>作&nbsp;者&nbsp;出&nbsp;版&nbsp;书&nbsp;籍&nbsp;页&nbsp;面</span>
{% endblock %}

{#表格#}
{% block con %}
    <table class="table table-bordered text-center">
        <thead>
        <tr>
            <th class="text-center">书名</th>
            <th class="text-center">出版日期</th>
            <th class="text-center">价格</th>
            <th class="text-center">出版社</th>
        </tr>
        </thead>
        <tbody>
        {# 表格内容 #}
        {% for book in book_list %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{{ book.publishDate|date:'Y-m-d' }}</td>
                {# 日期格式化输出 #}
                <td>{{ book.price }}</td>
                <td>
                    <a href=/book/{{ book.publish.pk }}/publish_list/>{{ book.publish.name }}</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock con %}

book_project/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>base</title>
    {% endblock %}
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <script src="/static/jquery-3.4.1.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>

</head>
<body>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

        </div>
    </div>
</div>
<div class="header">
    {% block head %}
    {% endblock head %}
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p>
            <h2>Hi: {{ request.user.username }}</h2><a href="/logout/">注销</a>
            </p>
        </div>
        <div class="col-md-9">
            {% block con %}
                <h4>content</h4>
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

book_project/templates/book.html
{% extends 'base.html' %}


{#标题#}
{% block title %}
    <title>book</title>
{% endblock title %}

{#头部信息#}
{% block head %}
    <span>图&nbsp;书&nbsp;管&nbsp;理&nbsp;页&nbsp;面</span>
{% endblock %}

{#表格#}
{% block con %}
    <ul class="nav nav-tabs active" role="tablist">
        <li role="presentation">
            <a href="#book" aria-controls="book" role="tab"
               data-toggle="tab">书籍</a></li>
        <li role="presentation"><a href="#publish" aria-controls="publish" role="tab" data-toggle="tab">出版社</a>
        </li>
        <li role="presentation"><a href="#author" aria-controls="author" role="tab"
                                                  data-toggle="tab">作者</a>
        </li>
    </ul>
    {#####################################书籍页面######################################}
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="book">
            <table class="table table-bordered text-center">
                <thead>
                <tr>
                    {% for book_label in book_form %}
                        <th class="text-center">{{ book_label.label }}</th>
                    {% endfor %}
                    <th class="text-center">删除操作</th>
                    <th class="text-center">编辑操作</th>
                </tr>
                </thead>
                <tbody>
                {# 表格内容，从数据库传入#}
                {% for book_obj in book_values %}
                    <tr>
                        <td>{{ book_obj.title }} </td>
                        <td>{{ book_obj.publishDate|date:'Y-m-d' }} </td>
                        {# 时间格式化输出 #}
                        <td>{{ book_obj.price }} </td>
                        <td>
                            <a href={{ book_obj.publish.pk }}/publish_list/>{{ book_obj.publish.name }}</a>
                        </td>
                        <td> {% for author_obj in book_obj.authors.all %}{# 取出书籍的所有作者 #}
                            {% if forloop.last %}{# 判断取出的是否是最后一个值 #}
                                <a href={{ author_obj.pk }}/author_list/>{{ author_obj.name }}</a>
                                {# 最后一个值后面不加逗号 #}
                            {% else %}
                                <a href={{ author_obj.pk }}/author_list/>{{ author_obj.name }}</a>,
                            {% endif %}
                        {% endfor %}
                        </td>
                        <td>
                            <a href="{{ book_obj.nid }}/delete_book" class="btn btn-danger">删除</a>
                        </td>
                        <td>
                            <a href="{{ book_obj.nid }}/change_book" class="btn btn-info"
                               data-target="#myModal" data-toggle="modal">编辑</a>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            <a href="/add_books/" class="btn btn-success " role="button"><span
                    class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></a>
        </div>
        {#####################################出版社页面######################################}
        <div role="tabpanel" class="tab-pane" id="publish">
            <table class="table table-bordered text-center">
                <thead>
                <tr>
                    {% for publish_label in publish_form %}
                        <th class="text-center">{{ publish_label.label }}</th>
                    {% endfor %}
                    <th class="text-center">删除操作</th>
                    <th class="text-center">编辑操作</th>
                </tr>
                </thead>
                <tbody>
                {# 表格内容，从数据库传入#}
                {% for publish_obj in publish_values %}
                    {# {'nid': 1, 'name': '人民出版社', 'city': '北京', 'email': '123@qq.com'} #}
                    <tr>
                        <td>{{ publish_obj.name }} </td>
                        <td>{{ publish_obj.city }} </td>
                        <td>{{ publish_obj.email }} </td>
                        <td>
                            <a href="{{ publish_obj.nid }}/delete_publish" class="btn btn-danger">删除</a>
                        </td>
                        <td>
                            <a href="{{ publish_obj.nid }}/change_publish" class="btn btn-info"
                               data-target="#myModal" data-toggle="modal">编辑</a>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            <a href="/add_publish/" class="btn btn-success " role="button"><span
                    class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></a>
        </div>
        {#####################################作者页面######################################}
        <div role="tabpanel" class="tab-pane" id="author">
            <table class="table table-bordered text-center">
                <thead>
                <tr>
                    {% for author_label in author_form %}
                        <th class="text-center">{{ author_label.label }}</th>
                    {% endfor %}
                    <th class="text-center">删除操作</th>
                    <th class="text-center">编辑操作</th>
                </tr>
                </thead>
                <tbody>
                {# 表格内容，从数据库传入#}
                {% for author_obj in author_values %}
                    <tr>
                        <td>{{ author_obj.name }} </td>
                        <td>{{ author_obj.age }} </td>
                        <td>
                            <a href="{{ author_obj.nid }}/delete_author" class="btn btn-danger">删除</a>
                        </td>
                        <td>
                            <a href="{{ author_obj.nid }}/change_author" class="btn btn-info"
                               data-target="#myModal" data-toggle="modal">编辑</a>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
            <a href="/add_author/" class="btn btn-success " role="button"><span
                    class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></a>
        </div>
    </div>
    <script src="/static/js/book.js"></script>
{% endblock con %}

book_project/templates/change_author.html
{% extends 'changes.html' %}
{# id #}
{% block id %}
    <input type="text" value={{ author_obj.nid }}>
{% endblock id %}
{#标题#}
{% block modal_title %}
    <h3>作者：{{ author_obj.name }}</h3>
{% endblock modal_title %}


{#form表单#}
{% block modal_table %}
    <form>
        {% csrf_token %}
        <div class="row">
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_name">{{ form.name.label }}</label>
                <input type="text" id="id_name" value={{ author_obj.name }} class="form-control">
                <span style="color: red" class="pull-right error"></span>
            </p>
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_age">{{ form.age.label }}</label>
                <input type="text" id="id_age" value={{ author_obj.age }} class="form-control">
                <span style="color: red" class="pull-right error"></span>
            </p>
        </div>
    </form>
{% endblock modal_table %}
{% block js %}
    <script src="/static/js/change_author.js"></script>
{% endblock js %}

book_project/templates/change_book.html
{% extends 'changes.html' %}
{# id #}
{% block id %}
    <input type="text" value={{ book_obj.nid }}>
{% endblock id %}
{#标题#}
{% block modal_title %}
    <h3>书籍：{{ book_obj.title }}</h3>
{% endblock modal_title %}


{#form表单#}
{% block modal_table %}
    <form id="form">
        {% csrf_token %}
        <div class="row">
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_title">{{ form.title.label }}</label>
                <input type="text" id="id_title" name="title" value={{ book_obj.title }} class="form-control" readonly>
                <span style="color: red" class="pull-right error"></span>
            </p>
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_publishDate">{{ form.publishDate.label }}</label>
                <input type="text" id="id_publishDate" name="publishDate"
                       value={{ book_obj.publishDate|date:'Y-m-d' }} class="form-control">
                <span style="color: red" class="pull-right error"></span>
            </p>
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_price">{{ form.price.label }}</label>
                <input type="text" id="id_price" name="price" value={{ book_obj.price }} class="form-control">
                <span style="color: red" class="pull-right error"></span>
            </p>
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_publish">{{ form.publish.label }}</label>
                <select id="id_publish" class="form-control" name="publish">
                    {% for publish in publish_list %}
                        {% if book_obj.publish == publish %}
                            {# 判断是否是选中的值 #}
                            <option selected value="{{ publish.pk }}">{{ publish.name }}</option>
                        {% else %}
                            <option value="{{ publish.pk }}">{{ publish.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
                <span style="color: red" class="pull-right error"></span>
            </p>
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_author">{{ form.author.label }}</label>
                <select id="id_author" multiple class="form-control" name="author">
                    {% for author in author_list %}
                        {% if author in book_obj.authors.all %}
                            {# 判断是否是选中的值 #}
                            <option selected value="{{ author.pk }}">{{ author.name }}</option>
                        {% else %}
                            <option value="{{ author.pk }}">{{ author.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
                <span style="color: red" class="pull-right error"></span>
            </p>
        </div>
    </form>
{% endblock modal_table %}
{% block js %}
    <script src="/static/js/change_book.js"></script>
{% endblock js %}

book_project/templates/change_publish.html
{% extends 'changes.html' %}
{# id #}
{% block id %}
    <input type="text" value={{ publish_obj.nid }}>
{% endblock id %}
{#标题#}
{% block modal_title %}
    <h3>出版社：{{ publish_obj.name }}</h3>
{% endblock modal_title %}


{#form表单#}
{% block modal_table %}
    <form>
        {% csrf_token %}
        <div class="row">
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_name">{{ form.name.label }}</label>
                <input type="text" id="id_name" value={{ publish_obj.name }} class="form-control">
                <span style="color: red" class="pull-right error"></span>
            </p>
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_city">{{ form.city.label }}</label>
                <input type="text" id="id_city" value={{ publish_obj.city }} class="form-control">
                <span style="color: red" class="pull-right error"></span>
            </p>
            <p class="col-xs-6 col-md-offset-2">
                <label for="id_email">{{ form.email.label }}</label>
                <input type="text" id="id_email" value={{ publish_obj.email }} class="form-control">
                <span style="color: red" class="pull-right error"></span>
            </p>
        </div>
    </form>
{% endblock modal_table %}
{% block js %}
    <script src="/static/js/change_publish.js"></script>
{% endblock js %}

book_project/templates/changes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="/static/jquery-3.4.1.js"></script>
</head>
<body>
<div id="chang_id" style="display: none">
    {% block id %}

    {% endblock id %}
</div>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">
        {% block modal_title %}
            modal title
        {% endblock modal_title %} </h4>
</div>
<div class="modal-body">
    {% block modal_table %}
        ...
    {% endblock modal_table %}
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary" >Save changes</button>
</div>
{% block js %}

{% endblock js %}
</body>
</html>

book_project/templates/login.html
{% extends 'base.html' %}


{#标题#}
{% block title %}
    <title>login</title>
    <link rel="stylesheet" href="/static/css/login.css">
{% endblock title %}

{#头部信息#}
{% block head %}
    <span>登&nbsp;录&nbsp;页&nbsp;面</span>
{% endblock %}

{#form表单#}
{% block con %}
    <form>
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-xs-6">
                <label for="username">用户名</label>
                <input type="text" class="form-control" id="username">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-6">
                <label for="pwd">密码</label>
                <input type="password" class="form-control" id="pwd">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-xs-6">
                <label for="validCode">验证码</label>
                <div class="row">
                    <div class="col-xs-4">
                        <input type="text" class="form-control" id="validCode">
                    </div>
                    <div class="col-xs-6">
                        <img src="/get_img/" alt="验证码" width="270" height="40" id="validCodeImg">
                    </div>
                </div>
            </div>

        </div>

        <input type="button" class="btn btn-success" id="login_btn" value="登录">
        <button class="btn btn-default">
            <a href="/register/">注册</a>
        </button>
        <span class="error"></span>
    </form>

    <script src="/static/js/login.js"></script>
{% endblock con %}

book_project/templates/publish_list.html
{% extends 'base.html' %}


{#标题#}
{% block title %}
    <title>publish_list</title>
{% endblock title %}

{#头部信息#}
{% block head %}
    <span>出&nbsp;版&nbsp;社&nbsp;旗&nbsp;下&nbsp;的&nbsp;书&nbsp;籍&nbsp;页&nbsp;面</span>
{% endblock %}

{#表格#}
{% block con %}
    <table class="table table-bordered text-center">
        <thead>
        <tr>
            <th class="text-center">书名</th>
            <th class="text-center">出版日期</th>
            <th class="text-center">价格</th>
            <th class="text-center">作者</th>
        </tr>
        </thead>
        <tbody>
        {# 表格内容 #}
        {% for book in book_list %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{{ book.publishDate|date:'Y-m-d' }}</td>
                {# 日期格式化输出 #}
                <td>{{ book.price }}</td>
                <td>
                    {% for author in book.authors.all %}{# 拿到所有作者 #}
                        {% if forloop.last %}{# 判断是否是最后一个值 #}
                            <a href="/book/{{ author.pk }}/author_list/">{{ author.name }}</a>{# 最后一个值不加逗号 #}
                        {% else %}
                            <a href="/book/{{ author.pk }}/author_list/">{{ author.name }}</a>,
                        {% endif %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock con %}

book_project/templates/register.html
{% extends 'base.html' %}


{#标题#}
{% block title %}
    <title>register</title>
    <link rel="stylesheet" href="/static/css/register.css">
{% endblock title %}

{#头部信息#}
{% block head %}
    <span>注&nbsp;册&nbsp;页&nbsp;面</span>
{% endblock %}

{#form表单#}
{% block con %}
    <form id="form">
        {% csrf_token %}
        {############## 普通字段用for循环 ##############}
        {% for field in form %}
            <div class="row">
                <div class="form-group col-xs-6">
                    <label for="{{ field.auto_id }}">{{ field.label }}</label>
                    {# 会自动添加id_+field#}
                    {{ field }} <span class="error pull-right"></span>
                </div>
            </div>
        {% endfor %}
        {############## 头像字段 ##############}
        <div class="form-group">
            <label for="avatar">头像
                <img src="/media/avatars/default.png" alt="头像" width="60" height="60" id="avatar_img">
            </label>
            <input type="file" id="avatar">
        </div>
        <input type="button" class="btn btn-success reg_btn col-md-offset-2 btn-lg" value="注册"><span class="error"></span>
    </form>
    <script src="/static/js/register.js"></script>
{% endblock con %}